DROP TABLE IF EXIST albums;

CREATE TABLE albums (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
artist VARCHAR(50) ,
name VARCHAR (50),
release_date DATE ,
sales FLOAT,
genre VARCHAR (100),
PRIMARY KEY (id)
);